// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgrmsdkohheeuxzlfdrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impncm1zZGtvaGhlZXV4emxmZHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwOTc4MDcsImV4cCI6MjA1MTY3MzgwN30.WSEYfEZS3AYTa_OY3gnP9ig1iK9133e1NwJosnvfPR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);